## 01 只打印或显示numpy数组rand_arr的小数点后3位

* rand_arr = np.random.random([5, 3])

【知识点：输入和输出】

* 如何在numpy数组中只打印小数点后三位？

In [1]:
import numpy as np

In [3]:
np.set_printoptions(precision=3)
rand_arr = np.random.random([5, 3])
print(rand_arr)

[[0.861 0.289 0.853]
 [0.102 0.883 0.962]
 [0.831 0.744 0.24 ]
 [0.965 0.787 0.366]
 [0.93  0.321 0.12 ]]


## 02 将numpy数组a中打印的项数限制为最多6个元素

【知识点：输入和输出】

* 如何限制numpy数组输出中打印的项目数？

In [4]:
np.set_printoptions(threshold=6)
rand_arr = np.random.random([1, 20])
print(rand_arr)

[[0.97  0.341 0.131 ... 0.926 0.246 0.779]]


## 03 打印完整的numpy数组a而不中断

【知识点：输入和输出】

* 如何打印完整的numpy数组而不中断？

In [5]:
np.set_printoptions(threshold=np.iinfo(np.int).max)
x = np.arange(50)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
